# Generated by Django 6.0.3 on 2026-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0024_fix_split_and_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeddocument',
            name='manifest_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mergeddocument',
            name='merge_attempt_count',
            field=models.IntegerField(default=0),
        ),
    ]
