# Generated by Django 6.0.3 on 2026-04-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_bridge', '0003_alter_assignmentbundle_status'),
        ('processing', '0025_mergeddocument_manifest_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpage',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_pages', to='desktop_bridge.assignmentbundle'),
        ),
    ]
