# Generated by Django 6.0.3 on 2026-04-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0026_submittedpage_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpage',
            name='bundle_version_id',
            field=models.UUIDField(blank=True, help_text='Atomic ID pairing all pages in a single bundle submission version', null=True),
        ),
    ]
