# Generated by Django 6.0.3 on 2026-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_resourceprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprofile',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Max pages per cycle'),
        ),
    ]
