# Generated by Django 6.0.3 on 2026-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetable',
            name='col_aligns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pagetable',
            name='col_widths',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Plain Text'), ('table_cell', 'Table Cell'), ('header', 'Header'), ('footer', 'Footer'), ('caption', 'Caption'), ('table', 'Table Area'), ('image', 'Image Area')], default='text', max_length=20),
        ),
    ]
