# Generated by Django 6.0.3 on 2026-03-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_pagetable_col_aligns_pagetable_col_widths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetable',
            name='row_colors',
            field=models.JSONField(default=list),
        ),
    ]
