# Generated by Django 6.0.3 on 2026-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0043_pagetable_row_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ocr_provider',
            field=models.CharField(blank=True, help_text="Service provider used for OCR (e.g., 'adobe', 'azure', 'tesseract')", max_length=50, null=True),
        ),
    ]
