# Generated by Django 6.0.3 on 2026-03-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0044_page_ocr_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetable',
            name='row_heights',
            field=models.JSONField(default=list, help_text='Array of row heights in percentages'),
        ),
    ]
