# Generated by Django 5.0.14 on 2026-03-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0045_pagetable_row_heights"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetable",
            name="is_manually_edited",
            field=models.BooleanField(default=False),
        ),
    ]
