# Generated by Django 6.0.3 on 2026-03-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0046_pagetable_is_manually_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_underlined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Plain Text'), ('table_cell', 'Table Cell'), ('header', 'Header'), ('footer', 'Footer'), ('caption', 'Caption'), ('table', 'Table Area'), ('image', 'Image Area'), ('line', 'Single Line'), ('underline', 'Underline'), ('double_line', 'Double Line')], default='text', max_length=20),
        ),
    ]
