# Generated by Django 6.0.3 on 2026-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0047_block_is_underlined_alter_block_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='font_variant',
            field=models.CharField(choices=[('normal', 'Normal'), ('superscript', 'Superscript'), ('subscript', 'Subscript')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', max_length=20),
        ),
    ]
