# Generated by Django 6.0.3 on 2026-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0048_block_font_variant_block_text_align"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="colspan",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="block",
            name="rowspan",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="block",
            name="semantic_role",
            field=models.CharField(
                choices=[
                    ("heading_1", "Heading 1"),
                    ("heading_2", "Heading 2"),
                    ("heading_3", "Heading 3"),
                    ("body_text", "Body Text"),
                    ("footnote", "Footnote"),
                    ("caption", "Caption"),
                ],
                default="body_text",
                help_text="Detected semantic role for layout reconstruction",
                max_length=30,
            ),
        ),
    ]
