# Generated by Django 6.0.3 on 2026-03-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0049_block_colspan_block_rowspan_block_semantic_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='line_height',
            field=models.FloatField(default=1.2, help_text='Relative line height for paragraph spacing'),
        ),
        migrations.AddField(
            model_name='block',
            name='z_index',
            field=models.IntegerField(default=0, help_text='Layering order for overlapping elements'),
        ),
    ]
