# Generated by Django 6.0.3 on 2026-03-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0050_block_line_height_block_z_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='complexity_score',
            field=models.PositiveIntegerField(default=1, help_text='Weighted complexity score (standardized to 1 for all pages)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='complexity_weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
