# Generated by Django 6.0.3 on 2026-04-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0051_alter_page_complexity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
