# Generated by Django 6.0.3 on 2026-04-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0053_document_final_word_fields'),
        ('processing', '0028_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Associated Job for strict bundle workflows (Legacy if null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processing.job'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pipeline_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('CONVERTING', 'Converting to PDF'), ('SPLITTING', 'Splitting Pages'), ('VALIDATING', 'Validating Pages'), ('SCORING', 'Scoring Complexity'), ('READY_TO_ASSIGN', 'Ready for Assignment'), ('ASSIGNING', 'Assigning to Resources'), ('IN_PROGRESS', 'Processing in Progress'), ('ALL_SUBMITTED', 'All Pages Submitted'), ('MERGING', 'Merging Pages'), ('MERGED', 'Merge Complete'), ('COMPLETED', 'Pipeline Completed'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected'), ('FAILED', 'Pipeline Failed')], db_index=True, default='UPLOADED', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
