# Generated by Django 6.0.3 on 2026-04-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_document_job_alter_document_pipeline_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='storage/converted/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='The PDF file used for OCR/Splitting', null=True, upload_to='storage/internal_processing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to='storage/finals/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='final_word_file',
            field=models.FileField(blank=True, null=True, upload_to='storage/3_final_merged_docx/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='storage/1_original_pdfs/%Y/%m/%d/'),
        ),
    ]
