# Generated by Django 6.0.3 on 2026-04-02 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0052_block_is_manually_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(help_text='Human-readable name of the machine', max_length=255)),
                ('machine_id', models.CharField(blank=True, default='', help_text='Hardware-based UUID', max_length=255)),
                ('agent_version', models.CharField(blank=True, default='', max_length=50)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desktop Device',
                'verbose_name_plural': 'Desktop Devices',
                'db_table': 'docpro_desktop_device',
            },
        ),
        migrations.CreateModel(
            name='AssignmentBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundle_index', models.PositiveIntegerField(help_text='Strict sequence index starting from 0')),
                ('page_start', models.PositiveIntegerField(help_text='Start page number (1-indexed)')),
                ('page_end', models.PositiveIntegerField(help_text='End page number (inclusive)')),
                ('page_numbers', models.JSONField(default=list, help_text='List of exact page numbers in this bundle')),
                ('source_pdf', models.FileField(help_text='Sealed PDF for this range', upload_to='desktop_bridge/source/%Y/%m/%d/')),
                ('result_pdf', models.FileField(blank=True, help_text='The edited PDF returned by the agent', null=True, upload_to='desktop_bridge/result/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('READY', 'Ready for Download'), ('LEASED', 'Leased to Device'), ('DOWNLOADED', 'Downloaded by Agent'), ('EDITING', 'Being Edited in ABBYY'), ('UPLOADED', 'Result Uploaded'), ('MERGED', 'Merged into Final PDF'), ('EXPIRED', 'Lease Expired'), ('FAILED', 'Processing Failed')], default='READY', max_length=20)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('manifest', models.JSONField(default=dict, help_text='JSON manifest shipped in the ZIP')),
                ('source_sha256', models.CharField(blank=True, default='', help_text='Checksum of the source PDF', max_length=64)),
                ('result_sha256', models.CharField(blank=True, default='', help_text='Checksum of the uploaded result', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='documents.document')),
                ('leased_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='desktop_bridge.desktopdevice')),
            ],
            options={
                'db_table': 'docpro_assignment_bundle',
                'indexes': [models.Index(fields=['status', 'lease_expires_at'], name='docpro_assi_status_5be0d9_idx'), models.Index(fields=['document', 'bundle_index'], name='docpro_assi_documen_3d31c4_idx')],
                'unique_together': {('document', 'bundle_index')},
            },
        ),
    ]
