# Generated by Django 6.0.3 on 2026-04-03 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_bridge', '0001_initial'),
        ('documents', '0052_block_is_manually_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Merge Pending'), ('SUCCESS', 'Merge Successful'), ('FAILED', 'Merge Failed'), ('PARTIAL', 'Partial Coverage')], default='PENDING', max_length=20)),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='desktop_bridge/merged/%Y/%m/%d/')),
                ('version_map', models.JSONField(default=dict, help_text='Map of page numbers to the specific PageVersion IDs used')),
                ('missing_pages', models.JSONField(default=list, help_text='List of page numbers missing during this merge attempt')),
                ('error_details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_manifests', to='documents.document')),
            ],
            options={
                'db_table': 'docpro_merge_manifest',
            },
        ),
        migrations.CreateModel(
            name='MergeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_logs', to='documents.document')),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='desktop_bridge.mergemanifest')),
            ],
            options={
                'db_table': 'docpro_merge_audit_log',
            },
        ),
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='The full uploaded PDF', upload_to='desktop_bridge/uploads/%Y/%m/%d/')),
                ('checksum', models.CharField(help_text='SHA256 checksum of the uploaded file', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='desktop_bridge.assignmentbundle')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='desktop_bridge.desktopdevice')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='documents.document')),
            ],
            options={
                'db_table': 'docpro_uploaded_pdf',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(help_text='1-indexed page number in the original document')),
                ('page_index_in_pdf', models.PositiveIntegerField(help_text='0-indexed position within the uploaded result_pdf')),
                ('slice_size', models.PositiveIntegerField(help_text='Number of pages in the bundle (smaller is better/more specific)')),
                ('source_checksum', models.CharField(blank=True, help_text='Checksum of the source page for change detection', max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_versions', to='desktop_bridge.assignmentbundle')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_versions', to='documents.document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.page')),
                ('uploaded_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_versions', to='desktop_bridge.uploadedpdf')),
            ],
            options={
                'db_table': 'docpro_page_version',
                'indexes': [models.Index(fields=['document', 'page_number', 'slice_size', 'updated_at'], name='docpro_page_documen_250869_idx')],
                'unique_together': {('uploaded_pdf', 'page_number')},
            },
        ),
    ]
