# Generated by Django 6.0.3 on 2026-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_bridge', '0002_mergemanifest_mergeauditlog_uploadedpdf_pageversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentbundle',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready for Download'), ('LEASED', 'Leased to Device'), ('DOWNLOADED', 'Downloaded by Agent'), ('EDITING', 'Being Edited in ABBYY'), ('UPLOADED', 'Result Uploaded'), ('COMPLETED', 'Bundle Completed & Approved'), ('MERGED', 'Merged into Final PDF'), ('EXPIRED', 'Lease Expired'), ('FAILED', 'Processing Failed')], default='READY', max_length=20),
        ),
    ]
