# Generated by Django 6.0.3 on 2026-04-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_bridge', '0003_alter_assignmentbundle_status'),
        ('processing', '0028_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentbundle',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='input_file',
            field=models.FileField(blank=True, help_text='Atomic input file (PDF)', null=True, upload_to='desktop_bridge/input/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The Job this bundle belongs to (Legacy if null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='processing.job'),
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='output_file',
            field=models.FileField(blank=True, help_text='Atomic output file (DOCX)', null=True, upload_to='desktop_bridge/output/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The specific user assigned to this atomic bundle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bundles', to=settings.AUTH_USER_MODEL),
        ),
    ]
