# Generated by Django 6.0.3 on 2026-04-04 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_bridge', '0004_assignmentbundle_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentbundle',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentbundle',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bundles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentbundle',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready for Download'), ('LEASED', 'Leased to Device'), ('DOWNLOADED', 'Downloaded by Agent'), ('EDITING', 'Being Edited in ABBYY'), ('UPLOADED', 'Result Uploaded'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Admin Approved'), ('REJECTED', 'Admin Rejected'), ('COMPLETED', 'Legacy: Bundle Completed & Approved'), ('MERGED', 'Merged into Final PDF'), ('EXPIRED', 'Lease Expired'), ('FAILED', 'Processing Failed')], default='READY', max_length=20),
        ),
    ]
