# Generated by Django 6.0.3 on 2026-04-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_bridge', '0005_assignmentbundle_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentbundle',
            name='input_file',
            field=models.FileField(blank=True, help_text='Atomic input file (PDF)', null=True, upload_to='storage/internal_bundles/input/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assignmentbundle',
            name='output_file',
            field=models.FileField(blank=True, help_text='Atomic output file (DOCX)', null=True, upload_to='storage/2_edited_bundles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assignmentbundle',
            name='result_pdf',
            field=models.FileField(blank=True, help_text='The edited PDF returned by the agent', null=True, upload_to='storage/2_edited_bundles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assignmentbundle',
            name='source_pdf',
            field=models.FileField(help_text='Sealed PDF for this range', upload_to='storage/internal_bundles/source/%Y/%m/%d/'),
        ),
    ]
