# Generated by Django 6.0.3 on 2026-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_bridge', '0006_alter_assignmentbundle_input_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentbundle',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Submission version counter'),
        ),
    ]
